# Sprint ディープラーニングフレームワーク2

# 公式Example

## 【問題1】公式Exampleを分担して実行

- 以下を実行
https://www.tensorflow.org/tutorials/keras/basic_regression

- 車に関する、7個の特徴量から燃費を推測する問題
- ３層のニューラルネットワークを用いた
-　結果としては、テストデータの正解値と予測値で散布図を表示したところ線形となったので、それなりの成果が出ているようだ
- １００エポック以上からロスが上がっているので、学習を止めた方が良い

## 【問題2】Iris（2値分類）をKerasで学習

In [1]:
"""
TensorFlowで実装したニューラルネットワークを使いIrisデータセットを2値分類する
"""
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
import tensorflow as tf
import matplotlib.pyplot as plt

# データセットの読み込み
dataset_path ="Iris.csv"
df = pd.read_csv(dataset_path)

# データフレームから条件抽出
df = df[(df["Species"] == "Iris-versicolor")|(df["Species"] == "Iris-virginica")]
y = df["Species"]
X = df.loc[:, ["SepalLengthCm", "SepalWidthCm", "PetalLengthCm", "PetalWidthCm"]]
y = np.array(y)
X = np.array(X)
# ラベルを数値に変換
y[y=='Iris-versicolor'] = 0
y[y=='Iris-virginica'] = 1
y = y.astype(np.int)[:, np.newaxis]

# trainとtestに分割
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)
# さらにtrainとvalに分割
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.2, random_state=0)



In [2]:
model = tf.keras.Sequential([
            tf.keras.layers.Dense(100, activation = tf.nn.relu, input_shape=(4,)),
            tf.keras.layers.Dense(100, activation = tf.nn.relu),
            tf.keras.layers.Dense(1, activation = tf.nn.sigmoid)])

model.compile(loss='binary_crossentropy',
              optimizer=tf.train.AdamOptimizer(learning_rate=0.01),
              metrics=['accuracy'])

W0127 16:24:54.174554 4446201280 deprecation.py:506] From /Users/takamoriyuki/.pyenv/versions/anaconda3-5.3.1/lib/python3.7/site-packages/tensorflow/python/ops/init_ops.py:1251: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
W0127 16:24:54.312721 4446201280 deprecation.py:323] From /Users/takamoriyuki/.pyenv/versions/anaconda3-5.3.1/lib/python3.7/site-packages/tensorflow/python/ops/nn_impl.py:180: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


In [3]:
X_train.shape

(64, 4)

In [4]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 100)               500       
_________________________________________________________________
dense_1 (Dense)              (None, 100)               10100     
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 101       
Total params: 10,701
Trainable params: 10,701
Non-trainable params: 0
_________________________________________________________________


In [5]:
history = model.fit(X_train, y_train,
                    batch_size=20,
                    epochs=100,
                    verbose=1)

Epoch 1/100
64/64 [==============================] - 0s 3ms/sample - loss: 0.8497 - acc: 0.5000
Epoch 2/100
64/64 [==============================] - 0s 240us/sample - loss: 0.6631 - acc: 0.6406
Epoch 3/100
64/64 [==============================] - 0s 253us/sample - loss: 0.5600 - acc: 0.5625
Epoch 4/100
64/64 [==============================] - 0s 345us/sample - loss: 0.5035 - acc: 0.7656
Epoch 5/100
64/64 [==============================] - 0s 379us/sample - loss: 0.4240 - acc: 0.9375
Epoch 6/100
64/64 [==============================] - 0s 281us/sample - loss: 0.4914 - acc: 0.6562
Epoch 7/100
64/64 [==============================] - 0s 284us/sample - loss: 0.4855 - acc: 0.6875
Epoch 8/100
64/64 [==============================] - 0s 248us/sample - loss: 0.5149 - acc: 0.6250
Epoch 9/100
64/64 [==============================] - 0s 349us/sample - loss: 0.3399 - acc: 0.8750
Epoch 10/100
64/64 [==============================] - 0s 311us/sample - loss: 0.2805 - acc: 0.9219
Epoch 11/100
64/64 [=

64/64 [==============================] - 0s 123us/sample - loss: 0.2020 - acc: 0.8906
Epoch 84/100
64/64 [==============================] - 0s 137us/sample - loss: 0.3231 - acc: 0.8750
Epoch 85/100
64/64 [==============================] - 0s 130us/sample - loss: 0.0973 - acc: 0.9375
Epoch 86/100
64/64 [==============================] - 0s 140us/sample - loss: 0.1153 - acc: 0.9375
Epoch 87/100
64/64 [==============================] - 0s 129us/sample - loss: 0.0967 - acc: 0.9375
Epoch 88/100
64/64 [==============================] - 0s 147us/sample - loss: 0.1417 - acc: 0.9375
Epoch 89/100
64/64 [==============================] - 0s 148us/sample - loss: 0.0653 - acc: 0.9844
Epoch 90/100
64/64 [==============================] - 0s 154us/sample - loss: 0.0611 - acc: 1.0000
Epoch 91/100
64/64 [==============================] - 0s 126us/sample - loss: 0.0958 - acc: 0.9531
Epoch 92/100
64/64 [==============================] - 0s 159us/sample - loss: 0.1283 - acc: 0.9219
Epoch 93/100
64/64 [===

In [6]:
y_pred_proba = model.predict(X_train)[:, 0]

# 確率を0, 1に変換
y_pred = np.where(y_pred_proba >0.5, 1, 0)

print("y_pred_proba", y_pred_proba)
print("y_pred", y_pred)

y_pred_proba [9.9646831e-01 1.3228953e-03 9.8513961e-01 7.7947974e-04 9.9117655e-01
 7.4751377e-03 7.6085329e-04 7.1415007e-03 9.8847318e-01 9.9176437e-01
 6.6092610e-04 9.5795333e-01 7.1525574e-03 6.2714028e-01 6.4192683e-01
 1.4682114e-03 1.7734513e-01 9.8462987e-01 1.9360483e-03 9.9873096e-01
 9.9954593e-01 7.0107579e-03 8.9735305e-01 9.9949580e-01 9.9905175e-01
 8.9084804e-03 9.9654657e-01 4.5332313e-04 9.9333346e-01 9.9734974e-01
 9.9802476e-01 9.9722791e-01 1.9849718e-02 9.8707151e-01 7.2488189e-03
 9.9991500e-01 9.9867541e-01 8.1253052e-04 1.0638833e-03 1.6502753e-01
 2.5096536e-04 8.3263403e-01 3.3255386e-01 1.7467141e-04 1.6741753e-03
 9.9611282e-03 9.9958503e-01 9.9998713e-01 4.0960312e-04 5.1632226e-03
 7.6451898e-04 9.9896383e-01 9.9762386e-01 9.9986148e-01 9.9940765e-01
 9.9034894e-01 3.4261644e-03 9.9632108e-01 8.0221373e-01 9.9923354e-01
 1.0303557e-03 7.0268810e-03 9.9523157e-01 8.9007115e-01]
y_pred [1 0 1 0 1 0 0 0 1 1 0 1 0 1 1 0 0 1 0 1 1 0 1 1 1 0 1 0 1 1 1 1 0 1 0

## 【問題3】Iris（多値分類）をKerasで学習

In [7]:
# データセットの読み込み
dataset_path ="Iris.csv"
df3 = pd.read_csv(dataset_path)


# データフレームから条件抽出
df3 = df3[(df3["Species"] == "Iris-versicolor")|(df3["Species"] == "Iris-virginica")|(df3["Species"] == "Iris-setosa")]
y = df3["Species"]
X = df3.loc[:, ["SepalLengthCm", "SepalWidthCm", "PetalLengthCm", "PetalWidthCm"]]
y = np.array(y)
X = np.array(X)
# ラベルを数値に変換
y[y=='Iris-setosa'] = 0
y[y=='Iris-versicolor'] = 1
y[y=='Iris-virginica'] = 2
y = y.astype(np.int)[:, np.newaxis]

# trainとtestに分割
X_train, X_test3, y_train, y_test3 = train_test_split(X, y, test_size=0.2, random_state=0)
# さらにtrainとvalに分割
X_train3, X_val3, y_train3, y_val3 = train_test_split(X_train, y_train, test_size=0.2, random_state=0)


from sklearn.preprocessing import OneHotEncoder
enc = OneHotEncoder(handle_unknown='ignore', sparse=False)
y_train_one_hot3 = enc.fit_transform(y_train3)#[:, np.newaxis])
y_test_one_hot3 = enc.transform(y_test3)#[:, np.newaxis])

print(y_train3.shape) # (60000,)
print(y_train_one_hot3.shape) # (60000, 10)
print(y_train_one_hot3.dtype) # float64

(96, 1)
(96, 3)
float64


In [8]:
model = tf.keras.Sequential([
            tf.keras.layers.Dense(50, activation = tf.nn.relu, input_shape=(4,)),
            tf.keras.layers.Dense(100, activation = tf.nn.relu),
            tf.keras.layers.Dense(3, activation = tf.nn.softmax)])

model.compile(loss='categorical_crossentropy',
              optimizer=tf.train.AdamOptimizer(learning_rate=0.01),
              metrics=['accuracy'])

In [9]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_3 (Dense)              (None, 50)                250       
_________________________________________________________________
dense_4 (Dense)              (None, 100)               5100      
_________________________________________________________________
dense_5 (Dense)              (None, 3)                 303       
Total params: 5,653
Trainable params: 5,653
Non-trainable params: 0
_________________________________________________________________


In [10]:
history = model.fit(X_train3, y_train_one_hot3,
                    batch_size=20,
                    epochs=100,
                    verbose=1)

Epoch 1/100
96/96 [==============================] - 0s 865us/sample - loss: 0.9294 - acc: 0.5938
Epoch 2/100
96/96 [==============================] - 0s 307us/sample - loss: 0.4738 - acc: 0.7812
Epoch 3/100
96/96 [==============================] - 0s 136us/sample - loss: 0.4206 - acc: 0.7188
Epoch 4/100
96/96 [==============================] - 0s 163us/sample - loss: 0.3226 - acc: 0.8333
Epoch 5/100
96/96 [==============================] - 0s 181us/sample - loss: 0.2405 - acc: 0.8646
Epoch 6/100
96/96 [==============================] - 0s 170us/sample - loss: 0.2196 - acc: 0.9271
Epoch 7/100
96/96 [==============================] - 0s 189us/sample - loss: 0.1897 - acc: 0.8854
Epoch 8/100
96/96 [==============================] - 0s 176us/sample - loss: 0.1212 - acc: 0.9688
Epoch 9/100
96/96 [==============================] - 0s 199us/sample - loss: 0.1062 - acc: 0.9688
Epoch 10/100
96/96 [==============================] - 0s 178us/sample - loss: 0.0941 - acc: 0.9688
Epoch 11/100
96/96 

Epoch 84/100
96/96 [==============================] - 0s 105us/sample - loss: 0.0244 - acc: 0.9792
Epoch 85/100
96/96 [==============================] - 0s 112us/sample - loss: 0.0216 - acc: 0.9896
Epoch 86/100
96/96 [==============================] - 0s 106us/sample - loss: 0.0255 - acc: 0.9896
Epoch 87/100
96/96 [==============================] - 0s 115us/sample - loss: 0.0227 - acc: 0.9896
Epoch 88/100
96/96 [==============================] - 0s 126us/sample - loss: 0.0221 - acc: 1.0000
Epoch 89/100
96/96 [==============================] - 0s 105us/sample - loss: 0.0367 - acc: 0.9688
Epoch 90/100
96/96 [==============================] - 0s 102us/sample - loss: 0.0426 - acc: 0.9896
Epoch 91/100
96/96 [==============================] - 0s 89us/sample - loss: 0.0790 - acc: 0.9792
Epoch 92/100
96/96 [==============================] - 0s 113us/sample - loss: 0.2026 - acc: 0.9271
Epoch 93/100
96/96 [==============================] - 0s 120us/sample - loss: 0.0519 - acc: 0.9792
Epoch 94/10

In [11]:
y_pred_proba = model.predict(X_test3)#[:, 0]


# 確率を0,1,2に変換
y_pred3 = np.argmax(y_pred_proba , axis=1)

print("y_pred_proba", y_pred_proba)
print("y_pred", y_pred3)


y_pred_proba [[3.00842395e-09 9.96846720e-05 9.99900341e-01]
 [6.98223157e-05 9.99915361e-01 1.47973560e-05]
 [1.00000000e+00 1.89883465e-09 1.30317762e-21]
 [5.02804332e-09 2.44648574e-04 9.99755323e-01]
 [9.99999166e-01 7.83067435e-07 1.75317109e-17]
 [3.66197524e-11 1.10757037e-05 9.99988914e-01]
 [9.99999881e-01 1.41575384e-07 2.18913535e-18]
 [4.64889345e-05 9.99630213e-01 3.23259883e-04]
 [5.53820100e-05 9.99240637e-01 7.04024686e-04]
 [4.53017965e-05 9.99947548e-01 7.09792448e-06]
 [8.78590853e-08 1.16239034e-03 9.98837531e-01]
 [5.14846397e-05 9.99764979e-01 1.83571959e-04]
 [9.33427073e-05 9.95948672e-01 3.95800732e-03]
 [9.55110154e-05 9.98047352e-01 1.85705384e-03]
 [1.18191543e-04 9.70468342e-01 2.94133890e-02]
 [9.99995470e-01 4.50040579e-06 1.50948511e-16]
 [1.54552545e-04 9.82737958e-01 1.71074998e-02]
 [2.17985275e-04 9.64927733e-01 3.48542519e-02]
 [9.99992371e-01 7.59669729e-06 7.88014074e-16]
 [1.00000000e+00 1.16498455e-08 3.52661733e-20]
 [5.47323715e-08 4.69630962

In [12]:
np.reshape(y_test3, (-1))

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0])

## 【問題4】House PricesをKerasで学習

In [15]:
# データセットの読み込み
dataset_path ="./housing_price_train.csv"
df = pd.read_csv(dataset_path)
# データフレームから条件抽出

y = df["SalePrice"]
X = df.loc[:, ["GrLivArea", "YearBuilt"]]
y = np.array(y)
X = np.array(X)
y = y[:, np.newaxis]
# yを対数変換
X = np.log(X)


# trainとtestに分割
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)
# さらにtrainとvalに分割
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.2, random_state=0)

In [17]:
# ハイパーパラメータ
learning_rate = 0.01
batch_size = 10
num_epochs = 30

model = tf.keras.Sequential()
model.add(tf.keras.layers.Dense(50, activation = tf.nn.relu, input_shape=(2,)))
model.add(tf.keras.layers.Dense(100, activation = tf.nn.relu))
model.add(tf.keras.layers.Dense(1))

model.summary()

model.compile(loss='mean_squared_error',
              optimizer=tf.train.AdamOptimizer(learning_rate=learning_rate),
              metrics=['mean_squared_error'])

history = model.fit(X_train, y_train,
                    batch_size=batch_size,
                    epochs=num_epochs,
                    verbose=0,
                    validation_data=(X_val, y_val))

y_pred = model.predict(X_train)

# 指標値
score = model.evaluate(X_test, y_test, verbose=0)
print('Test loss:', score[0])
print('Test mse:', score[1])

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_6 (Dense)              (None, 50)                150       
_________________________________________________________________
dense_7 (Dense)              (None, 100)               5100      
_________________________________________________________________
dense_8 (Dense)              (None, 1)                 101       
Total params: 5,351
Trainable params: 5,351
Non-trainable params: 0
_________________________________________________________________
Test loss: 6261673843.7260275
Test mse: 6261673500.0


## 【問題5】MNISTをKerasで学習

In [19]:
mnist = tf.keras.datasets.mnist

(X_train, y_train), (X_test, y_test) = mnist.load_data()
# 平滑化
X_train = X_train.reshape(-1, 784)
X_test = X_test.reshape(-1, 784)
# 前処理
X_train = X_train.astype(np.float)
X_test = X_test.astype(np.float)
X_train /= 255
X_test /= 255
y_train = np.eye(10)[y_train]
y_test = np.eye(10)[y_test]

X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.2, random_state=0)


In [21]:
# ハイパーパラメータ
learning_rate = 0.01
batch_size = 10
num_epochs = 10

model = tf.keras.Sequential()
model.add(tf.keras.layers.Dense(500, activation = tf.nn.relu, input_shape=(784,)))
model.add(tf.keras.layers.Dense(100, activation = tf.nn.relu))
model.add(tf.keras.layers.Dense(10, activation = tf.nn.softmax))

model.summary()

model.compile(loss='categorical_crossentropy',
              optimizer=tf.train.AdamOptimizer(learning_rate=learning_rate),
              metrics=['accuracy'])

history = model.fit(X_train, y_train,
                    batch_size=batch_size,
                    epochs=num_epochs,
                    verbose=1,
                    validation_data=(X_val, y_val))

y_pred_proba = model.predict(X_train)

# 確率の一番高いインデックスに変換
y_pred = np.argmax(y_pred_proba, axis=1)

# 指標値計算
score = model.evaluate(X_test, y_test, verbose=0)
print('Test loss:', score[0])
print('Test accuracy:', score[1])

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_9 (Dense)              (None, 500)               392500    
_________________________________________________________________
dense_10 (Dense)             (None, 100)               50100     
_________________________________________________________________
dense_11 (Dense)             (None, 10)                1010      
Total params: 443,610
Trainable params: 443,610
Non-trainable params: 0
_________________________________________________________________
Train on 48000 samples, validate on 12000 samples
Epoch 1/10
48000/48000 [==============================] - 20s 417us/sample - loss: 0.3808 - acc: 0.8982 - val_loss: 0.2824 - val_acc: 0.9287
Epoch 2/10
48000/48000 [==============================] - 19s 388us/sample - loss: 0.2773 - acc: 0.9337 - val_loss: 0.2845 - val_acc: 0.9391
Epoch 3/10
48000/48000 [======================