# 機械学習スクラッチ入門


In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

from sklearn.datasets import load_iris

from sklearn import linear_model
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier

from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import mean_squared_error

## 【問題1】train_test_splitのスクラッチ


In [2]:
def scratch_train_test_split(X, y, train_size=0.8):
    """
    検証用データを分割する。

    Parameters
    ----------
    X : 次の形のndarray, shape (n_samples, n_features)
      学習データ
    y : 次の形のndarray, shape (n_samples, )
      正解値
    train_size : float (0<train_size<1)
      何割をtrainとするか指定

    Returns
    ----------
    X_train : 次の形のndarray, shape (n_samples, n_features)
      学習データ
    X_test : 次の形のndarray, shape (n_samples, n_features)
      検証データ
    y_train : 次の形のndarray, shape (n_samples, )
      学習データの正解値
    y_test : 次の形のndarray, shape (n_samples, )
      検証データの正解値
    """
    X_train_size = int(len(X)*train_size)
    y_train_size = int(len(y)*train_size)
    
    X_train = X[:X_train_size]
    X_test = X[X_train_size:]
    y_train = y[:y_train_size]
    y_test = y[y_train_size:]
    
    

    return X_train, X_test, y_train, y_test

In [3]:
X_ndarray = np.array(list(range(50))).reshape((25,2))
y_ndarray = np.array(list(range(25)))


In [4]:
X_train, X_test, y_train, y_test = scratch_train_test_split(X_ndarray,y_ndarray)

In [5]:
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(20, 2) (5, 2) (20,) (5,)


# scikit-learnを用いて機械学習を行うコードを作成


## 分類問題

In [6]:
data = load_iris()
data_iris_X = data.data[data.target!=0]
data_iris_y = data.target[data.target!=0]

### シンプルデータセット1作成コード

In [7]:
np.random.seed(seed=0)
n_samples = 500
f0 = [-1, 2]
f1 = [2, -1]
cov = [[1.0,0.8], [0.8, 1.0]]

f0 = np.random.multivariate_normal(f0, cov, int(n_samples/2))
f1 = np.random.multivariate_normal(f1, cov, int(n_samples/2))

X1 = np.concatenate((f0, f1))
y1 = np.concatenate((np.ones((int(n_samples/2))), np.ones((int(n_samples/2))) *(-1))).astype(np.int)

random_index = np.random.permutation(np.arange(n_samples))
X1 = X1[random_index]
y1 = y1[random_index]

### シンプルデータセット２作成コード

In [8]:
X2 = np.array([[-0.44699 , -2.8073  ],[-1.4621  , -2.4586  ],
       [ 0.10645 ,  1.9242  ],[-3.5944  , -4.0112  ],
       [-0.9888  ,  4.5718  ],[-3.1625  , -3.9606  ],
       [ 0.56421 ,  0.72888 ],[-0.60216 ,  8.4636  ],
       [-0.61251 , -0.75345 ],[-0.73535 , -2.2718  ],
       [-0.80647 , -2.2135  ],[ 0.86291 ,  2.3946  ],
       [-3.1108  ,  0.15394 ],[-2.9362  ,  2.5462  ],
       [-0.57242 , -2.9915  ],[ 1.4771  ,  3.4896  ],
       [ 0.58619 ,  0.37158 ],[ 0.6017  ,  4.3439  ],
       [-2.1086  ,  8.3428  ],[-4.1013  , -4.353   ],
       [-1.9948  , -1.3927  ],[ 0.35084 , -0.031994],
       [ 0.96765 ,  7.8929  ],[-1.281   , 15.6824  ],
       [ 0.96765 , 10.083   ],[ 1.3763  ,  1.3347  ],
       [-2.234   , -2.5323  ],[-2.9452  , -1.8219  ],
       [ 0.14654 , -0.28733 ],[ 0.5461  ,  5.8245  ],
       [-0.65259 ,  9.3444  ],[ 0.59912 ,  5.3524  ],
       [ 0.50214 , -0.31818 ],[-3.0603  , -3.6461  ],
       [-6.6797  ,  0.67661 ],[-2.353   , -0.72261 ],
       [ 1.1319  ,  2.4023  ],[-0.12243 ,  9.0162  ],
       [-2.5677  , 13.1779  ],[ 0.057313,  5.4681  ]])
y2 = np.array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])


## 【問題2】 分類問題を解くコードの作成

In [9]:
def logistic_pred(X, y):
    print("logistic")
    logistic = linear_model.SGDClassifier(max_iter=1000, tol=1e-3, loss="log")
    pred_class(X, y, logistic)

def svm_pred(X, y):
    print("svm")
    svm = SVC(gamma='auto')
    pred_class(X, y, svm)

def decision_tree_pred(X, y):
    print("decision_tree")
    decision_tree = DecisionTreeClassifier(random_state=0)
    pred_class(X, y, decision_tree)

def pred_class(X, y, model):
    X_train, X_test, y_train, y_test = scratch_train_test_split(X, y, train_size=0.8)
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    evaluate(y_test, y_pred)
    print()
    
def evaluate(y_true, y_pred):
    print("accuracy =", accuracy_score(y_true, y_pred))
    print("precision =", precision_score(y_true, y_pred, average='macro'))
    print("recall =", recall_score(y_true, y_pred, average='macro'))
    print("f1 =", f1_score(y_true, y_pred, average='macro'))
    print(confusion_matrix(y_true, y_pred))

In [10]:
datas = [[data_iris_X, data_iris_y], [X1, y1], [X2, y2]]

for data in datas:
    X, y = data
    logistic_pred(X, y)
    svm_pred(X, y)
    decision_tree_pred(X, y)

logistic
accuracy = 1.0
precision = 1.0
recall = 1.0
f1 = 1.0
[[20]]

svm
accuracy = 0.9
precision = 0.5
recall = 0.45
f1 = 0.4736842105263158
[[ 0  0]
 [ 2 18]]

decision_tree
accuracy = 0.9
precision = 0.5
recall = 0.45
f1 = 0.4736842105263158
[[ 0  0]
 [ 2 18]]

logistic
accuracy = 1.0
precision = 1.0
recall = 1.0
f1 = 1.0
[[59  0]
 [ 0 41]]

svm
accuracy = 1.0
precision = 1.0
recall = 1.0
f1 = 1.0
[[59  0]
 [ 0 41]]

decision_tree
accuracy = 1.0
precision = 1.0
recall = 1.0
f1 = 1.0
[[59  0]
 [ 0 41]]

logistic
accuracy = 0.375
precision = 0.5
recall = 0.1875
f1 = 0.2727272727272727
[[0 0]
 [5 3]]

svm
accuracy = 0.375
precision = 0.5
recall = 0.1875
f1 = 0.2727272727272727
[[0 0]
 [5 3]]

decision_tree
accuracy = 0.375
precision = 0.5
recall = 0.1875
f1 = 0.2727272727272727
[[0 0]
 [5 3]]



/Users/takamoriyuki/.pyenv/versions/anaconda3-5.3.1/lib/python3.7/site-packages/sklearn/metrics/classification.py:1137: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
/Users/takamoriyuki/.pyenv/versions/anaconda3-5.3.1/lib/python3.7/site-packages/sklearn/metrics/classification.py:1137: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


## 回帰問題

## 【問題3】 回帰問題を解くコードの作成

In [11]:
housing_data = pd.read_csv("housing_price_train.csv")
X = np.array(housing_data[["GrLivArea", "YearBuilt"]])
y = np.array(housing_data["SalePrice"])

In [12]:
linear = linear_model.SGDRegressor(max_iter=1000, tol=1e-3)
X_train, X_test, y_train, y_test = scratch_train_test_split(X, y, train_size=0.8)
linear.fit(X_train, y_train)
y_pred = linear.predict(X_test)
mean_squared_error(y_test, y_pred)

1.0994133280609352e+31