# 行列積

## 【問題1】行列積を手計算する

In [ ]:
A{{-1,  2,  3},
     {4,  -5,  6},
     {7,  8,  -9}} 
*
B{{0,  2,  1},
    {0,  2,  -8},
    {2,  9,  -1}}

= {{6,  29,  -20},
     {12,  52,  38},
     {-18,  -51,  -48}}

= {{-1*0+2*0+3*2,  -1*2+2*2+3*9,  -1*1+2*(-8)+3*(-1)},
     {4*0+(-5)*0+6*2,  4*2+(-5)*2+6*9,  4*1+(-5)*(-8)+6*(-1)},
     {7*0+8*0+(-9)*2,  7*2+8*2+(-9)*9,  7*1+8*(-8)+(-9)*(-1)}}

##  【問題2】NumPyの関数による計算

In [10]:
import numpy as np

a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

ab_ndarray = a_ndarray @ b_ndarray

print(ab_ndarray)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


# 行列積のスクラッチ実装

##  【問題3】ある要素の計算を実装

In [69]:
# ２次元配列を返す関数

def matrix_multiplication (a_ndarray, b_ndarray):

    # 形を取り出す
    a_row, a_column = a_ndarray.shape
    b_row, b_column = b_ndarray.shape
    #print(a_row, a_column)
    
    if a_column != b_row:
        return print("Error: 行列の列と行が揃っていません")
        

    # 要素数a_row*b_columnのリスト作成
    arow_bcolumn_list = []
    #i行j列の内積
    ij_multiplication = []
    for i in range(a_row): # 行を一つずらしてループ
        for j in range(b_column): # i行固定で０〜b_column列までかける
            a_b = a_ndarray[i] * b_ndarray[:, j]# a配列i行＊b配列j行の積
            a_blist = sum(a_b)# a配列i行＊b配列j行の内積
            ij_multiplication.append(a_blist)
        
        arow_bcolumn_list.append(ij_multiplication)
        ij_multiplication = []
        #print(arow_bcolumn_list)

    ab_ndarray = np.array(arow_bcolumn_list).reshape(a_row, b_column)

    return(ab_ndarray)

print(matrix_multiplication(a_ndarray, b_ndarray))

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


## 【問題4】行列積を行う関数の作成


In [70]:
# ２次元配列を返す関数

def matrix_multiplication (a_ndarray, b_ndarray):

    # 形を取り出す
    a_row, a_column = a_ndarray.shape
    b_row, b_column = b_ndarray.shape
    #print(a_row, a_column)
    
    if a_column != b_row:# 例外処理
        return print("Error: 行列の列と行が揃っていません")
        

    # 要素数a_row*b_columnのリスト作成
    arow_bcolumn_list = []
    #i行j列の内積
    ij_multiplication = []
    for i in range(a_row): # 行を一つずらしてループ
        for j in range(b_column): # i行固定で０〜b_column列までかける
            a_b = a_ndarray[i] * b_ndarray[:, j]# a配列i行＊b配列j行の積
            a_blist = sum(a_b)# a配列i行＊b配列j行の内積
            ij_multiplication.append(a_blist)
        
        arow_bcolumn_list.append(ij_multiplication)
        ij_multiplication = []
        #print(arow_bcolumn_list)

    ab_ndarray = np.array(arow_bcolumn_list).reshape(a_row, b_column)

    return(ab_ndarray)

print(matrix_multiplication(a_ndarray, b_ndarray))



[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


# 行列積が定義されない組み合わせの行列

## 【問題5】計算が定義されない入力を判定する

In [72]:
d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])

print(matrix_multiplication(d_ndarray, e_ndarray))


Error: 行列の列と行が揃っていません
None


## 【問題6】転置

In [64]:
print(matrix_multiplication(d_ndarray.T, e_ndarray))

[[ 33 -28   9]
 [-48  41  -6]
 [  9  -6  45]]
